# Generated by Django 4.2.13 on 2024-05-26 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpagegalleryimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPageGalleryImage',
        ),
    ]
